name: 'Create derived files and Validate'
#description: ''
inputs:
  press:
    description: 'list of press codes'
    required: true
  requireTaxonomiesTranslations:
    description: 'require every term in common taxonomies to be translated'
    required: false
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      run: echo "REQ_TRANSLATION=${{ inputs.requireTaxonomiesTranslations || '1' }}" >> $GITHUB_ENV
      shell: bash
    - name: Validate
      id: validate
      working-directory: ${{github.workspace}}/PressMint
      run: |
        INTYPES=("" ".ana")
        STATUS=0
        for INTYPE in "${INTYPES[@]}"; do
          TYPE="TEI${INTYPE}"
          ROOT="Samples/PressMint-${{inputs.press}}/PressMint-${{inputs.press}}${INTYPE}.xml"
          if [ ! -f "$ROOT" ]; then
              echo "::warning title=Corpus root is missing::$ROOT not found"
          else
            echo "::notice:: Running validation for ParlaMint-${{inputs.press}}.$TYPE"
              make validate-TEI-${{inputs.press}}  2>&1 \
                | sed "s/^\(.*\)\(\berror\b\)/::error::\1\2/i;s/^\(.*\)\(\bwarn\)/::warning::\1\2/i;"  \
                | tee PressMint-${{inputs.press}}.$TYPE.log
              grep -iq error PressMint-${{inputs.press}}.$TYPE.log \
                && echo "::error:: PressMint-$parla.$TYPE validation FAILED" \
                && STATUS=1 \
                || echo "::notice:: ParlaMint-${{inputs.press}}.$TYPE validation PASSED"
          fi
        done
        echo "status=$STATUS" >> $GITHUB_OUTPUT
      shell: bash
      continue-on-error: true


    - name: Failing if anything is wrong
      if: ${{ steps.validate.outputs.status == '1' }}
      run: exit 1
      shell: bash
